# openapi2-appengine.yaml
swagger: '2.0'
info:
  title: sage-api transactions
  description: Sample API on API Gateway with an App Engine backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /:
    get:
      summary: This is the homepage
      operationId: home
      x-google-backend:
        address: https://sage-task.nw.r.appspot.com
        path_translation: [ APPEND_PATH_TO_ADDRESS ]
        jwt_audience: 272804158038-6kc250fms52o33b7dcfjrl1f9d8rripb.apps.googleusercontent.com
      security:
          - api_key: [] 
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /v1/api/transactions:
    get:
      summary: This returns all transactions
      operationId: get-transactions
      x-google-backend:
        address: https://sage-task.nw.r.appspot.com
        path_translation: [ APPEND_PATH_TO_ADDRESS ]
        jwt_audience: 272804158038-6kc250fms52o33b7dcfjrl1f9d8rripb.apps.googleusercontent.com
      security:
          - api_key: []  
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /v1/api/transactions/page_num/{page_number}:
    get:
      summary: This returns a transaction page
      operationId: get-page-transactions
      parameters:
        - in: path
          name: page_number
          required: true
          type: integer
          minimum: 1
          description: The number of the page
      x-google-backend:
        address: https://sage-task.nw.r.appspot.com
        path_translation: [ APPEND_PATH_TO_ADDRESS ]
        jwt_audience: 272804158038-6kc250fms52o33b7dcfjrl1f9d8rripb.apps.googleusercontent.com
      security:
          - api_key: []  
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /v1/api/transactions/get/symbol/{symbol}:
    get:
      summary: This returns transactions by symbol
      operationId: get-transactions-symbol
      parameters:
        - in: path
          name: symbol
          required: true
          type: string
          description: The symbol of transaction to filter 
      x-google-backend:
        address: https://sage-task.nw.r.appspot.com
        path_translation: [ APPEND_PATH_TO_ADDRESS ]
        jwt_audience: 272804158038-6kc250fms52o33b7dcfjrl1f9d8rripb.apps.googleusercontent.com
      security:
          - api_key: []  
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /v1/api/transactions/get/name/{name}:
    get:
      summary: This returns transactions by name
      operationId: get-transactions-name
      parameters:
        - in: path
          name: name
          required: true
          type: string
          description: The name of transaction to filter 
      x-google-backend:
        address: https://sage-task.nw.r.appspot.com
        path_translation: [ APPEND_PATH_TO_ADDRESS ]
        jwt_audience: 272804158038-6kc250fms52o33b7dcfjrl1f9d8rripb.apps.googleusercontent.com
      security:
          - api_key: []  
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /v1/api/transactions/add:
    post:
      summary: Creates a new transaction.
      operationId: create-transaction
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            $ref: '#/definitions/Model0'
      x-google-backend:
              address: https://sage-task.nw.r.appspot.com
              path_translation: [ APPEND_PATH_TO_ADDRESS ]
              jwt_audience: 272804158038-6kc250fms52o33b7dcfjrl1f9d8rripb.apps.googleusercontent.com
      security:
          - api_key: []                  
      responses:
        '201':
          description: A successful transaction created
          schema:
            type: string
  /v1/api/transactions/update/{symbol}/{currency}:
    put:
      summary: Update a new transaction.
      operationId: update-transaction
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            $ref: '#/definitions/Model0'
        - in: path
          name: symbol
          required: true
          type: string
          description: The symbol of transaction to filter
        - in: path
          name: currency
          required: true
          type: string
          description: The currency of transaction to filter      
      x-google-backend:
              address: https://sage-task.nw.r.appspot.com
              path_translation: [ APPEND_PATH_TO_ADDRESS ]
              jwt_audience: 272804158038-6kc250fms52o33b7dcfjrl1f9d8rripb.apps.googleusercontent.com
      security:
          - api_key: []                  
      responses:
        '201':
          description: A successful transaction created
          schema:
            type: string                                                     
  /v1/api/transactions/delete/symbol/{symbol}:
    delete:
      summary: This delete transactions by symbol
      operationId: delete-transactions-symbol
      parameters:
        - in: path
          name: symbol
          required: true
          type: string
          description: The symbol of transaction to delete
      x-google-backend:
        address: https://sage-task.nw.r.appspot.com
        path_translation: [ APPEND_PATH_TO_ADDRESS ]
        jwt_audience: 272804158038-6kc250fms52o33b7dcfjrl1f9d8rripb.apps.googleusercontent.com
      security:
          - api_key: []  
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /v1/api/transactions/delete/name/{name}:
    delete:
      summary: This delete transactions by name
      operationId: delete-transactions-name
      parameters:
        - in: path
          name: name
          required: true
          type: string
          description: The name of transaction to delete 
      x-google-backend:
        address: https://sage-task.nw.r.appspot.com
        path_translation: [ APPEND_PATH_TO_ADDRESS ]
        jwt_audience: 272804158038-6kc250fms52o33b7dcfjrl1f9d8rripb.apps.googleusercontent.com
      security:
          - api_key: []  
      responses:
        '200':
          description: A successful response
          schema:
            type: string          


definitions:
  Model0:
    properties:
      amount:
        type: number
        format: double
      currency:
        type: string
      date:
        type: integer
        format: int64
      name:
        type: string
      symbol:
        type: string  
        
securityDefinitions:
      # This section configures basic authentication with an API key.
      api_key:
        type: "apiKey"
        name: "key"
        in: "query"        