runtime: python39

instance_class: B2

# Remember - storing secrets in plaintext is potentially unsafe. Consider using
# something like https://cloud.google.com/secret-manager/docs/overview to help keep
# secrets secret.
env_variables:
  CLOUD_SQL_CONNECTION_NAME: sage-task:europe-west2:sage-transactions
  DB_USER: postgres
  DB_PASS: root
  DB_NAME: sagetransactions


manual_scaling:
  instances: 2  




